webroot/app/modules/productdetail/controllers/AController.php
<?php
namespace app\modules\productdetail\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\easyii\behaviors\SortableController;
use yii\widgets\ActiveForm;
use yii\web\UploadedFile;

use yii\easyii\components\Controller;
use app\modules\productdetail\models\ProductDetail;
use yii\easyii\helpers\Image;
use yii\easyii\behaviors\StatusController;

use yii\helpers\Url;

class AController extends Controller
{
    public function behaviors()
    {
        return [
            [
                'class' => SortableController::className(),
                'model' => ProductDetail::className(),
            ],
            [
                'class' => StatusController::className(),
                'model' => ProductDetail::className()
            ]
        ];
    }

    public function actionIndex()
    {
        $query = ProductDetail::find()->where(['status' => ProductDetail::STATUS_PUBLISHED]);

        $title = Yii::$app->request->get('title', "");
        $number = Yii::$app->request->get('number', "");
        $category = Yii::$app->request->get('category', "");
        $car_number = Yii::$app->request->get('car_number', "");
        $car_category = Yii::$app->request->get('car_category', "");

        if ($title != "") { $query->andFilterWhere(['like', 'title', $title]); }
        if ($number != "") { $query->andFilterWhere(['like', 'number', $number]); }
        if ($category != "") { $query->andFilterWhere(['like', 'category', $category]); }
        if ($car_number != "") { $query->andFilterWhere(['like', 'car_number', $car_number]); }
        if ($car_category != "") { $query->andFilterWhere(['like', 'car_category', $car_category]); }

        $data = new ActiveDataProvider([ 'query' => $query->sort(),  ]);

        $this->setReturnUrl(Url::current());

        return $this->render('index', [  'data' => $data, ]);
    }

    public function actionPending()
    {
        $data = new ActiveDataProvider([
            'query' => ProductDetail::find()->where(['status' => ProductDetail::STATUS_PENDING])->sort(),
        ]);

        $this->setReturnUrl(Url::current());

        return $this->render('index', [
            'data' => $data
        ]);
    }

    public function actionDeleted()
    {
        $data = new ActiveDataProvider([
            'query' => ProductDetail::find()->where(['status' => ProductDetail::STATUS_DELETED])->sort(),
        ]);

        $this->setReturnUrl(Url::current());

        return $this->render('index', [
            'data' => $data
        ]);
    }

    public function actionCreate()
    {
        $model = new ProductDetail;
        $model->status = ProductDetail::STATUS_PENDING;

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else{

                if($model->save()){
                    $this->flash('success', Yii::t('easyii', 'Created'));
                    return $this->redirect(['/admin/'.$this->module->id . '/a/edit/'. $model->id]);
                }
                else{
                    $this->flash('error', Yii::t('easyii', 'Create error. {0}', $model->formatErrors()));
                    return $this->refresh();
                }
            }
        }
        else {
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    public function actionEdit($id)
    {
        $model = ProductDetail::findOne($id);

        if($model === null){
            $this->flash('error', Yii::t('easyii', 'Not found'));
            return $this->redirect(['/admin/'.$this->module->id]);
        }

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else{

                if($model->save()){
                    $this->flash('success', Yii::t('easyii', 'Updated'));
                }
                else{
                    $this->flash('error', Yii::t('easyii', 'Update error. {0}', $model->formatErrors()));
                }
                return $this->refresh();
            }
        }
        else {
            return $this->render('edit', [
                'model' => $model
            ]);
        }
    }

    public function actionContentBlocks($id, $lang='en')
    {
        if(!($model = ProductDetail::findOne($id))){
            return $this->redirect(['/admin/'.$this->module->id]);
        }

        return $this->render('content_blocks', [
            'model' => $model,
            'lang' => $lang,
        ]);
    }


    public function actionDelete($id)
    {
        if(($model = ProductDetail::findOne($id))){
            $model->delete();
        } else {
            $this->error = Yii::t('easyii', 'Not found');
        }
        return $this->formatResponse(Yii::t('easyii', 'Deleted'));
    }

    public function actionClearImage($id)
    {
        $model = ProductDetail::findOne($id);

        if($model === null){
            $this->flash('error', Yii::t('easyii', 'Not found'));
        }
        else{
            $model->image = '';
            if($model->update()){
                @unlink(Yii::getAlias('@webroot').$model->image);
                $this->flash('success', Yii::t('easyii', 'Image cleared'));
            } else {
                $this->flash('error', Yii::t('easyii', 'Update error. {0}', $model->formatErrors()));
            }
        }
        return $this->back();
    }

    public function actionUp($id)
    {
        $status = Yii::$app->request->get('status');
        return $this->move($id, 'up', ['status' => $status]);
    }

    public function actionDown($id)
    {
        $status = Yii::$app->request->get('status');
        return $this->move($id, 'down', ['status' => $status]);
    }


}

webroot/app/modules/productdetail/views/a/_form.php
<?php
//引入模块
use yii\easyii\widgets\DateTimePicker;
use yii\easyii\helpers\Image;
use yii\easyii\widgets\TagsInput;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\easyii\widgets\Redactor;
//use app\modules\seo\widgets\Form;
use app\modules\photolibrary\widgets\Upload;

//定义变量
$module = $this->context->module->id;
$states = $model->states();
?>

<!--表单内容起始位置-->
<?php $form = ActiveForm::begin([
    'enableAjaxValidation' => true,
    'options' => ['enctype' => 'multipart/form-data', 'class' => 'model-form']
]); ?>

<!--添加标题模块-->

<div class="row">
    <div class="col-lg-6 col-md-6"><?= $form->field($model, 'title')->label('产品名称') ?></div>
    <div class="col-lg-6 col-md-6"><?= $form->field($model, 'slug')->label('产品标识 Slug') ?></div>
</div>


<!--添加状态模块-->
<div class="row">
    <div class="col-lg-6 col-md-6">
        <?= $form->field($model, 'status')->dropDownList($states)->label('产品状态')?>
    </div>
    <div class="col-lg-6 col-md-6">
        <?= $form->field($model, 'publish_time')->label('发布时间')->widget(DateTimePicker::className()); ?>
    </div>
</div>
<!--添加时间线模块-->
<div class="row">
    <div class="col-lg-6 col-md-6">
        <?= $form->field($model, 'updated_at')->widget(DateTimePicker::className(), ['disabled' => 'disabled']); ?>
    </div>
    <div class="col-lg-6 col-md-6">
        <?= $form->field($model, 'created_at')->widget(DateTimePicker::className(), ['disabled' => 'disabled']); ?>
    </div>
</div>

<!--添加产品模块-->

<div class="row">
    <div class="col-lg-12 col-md-12"><?= $form->field($model, 'pm')->label('产品经理') ?></div>
    <div class="col-lg-12 col-md-12"><?= $form->field($model, 'pm_info')->label('产品特色') ?></div>
</div>

<div class="row">
    <div class="col-lg-6 col-md-6"><?= $form->field($model, 'category')->label('产品类型') ?></div>
    <div class="col-lg-6 col-md-6"><?= $form->field($model, 'number') ->label('产品件号') ?></div>
</div>


<div class="row">
    <div class="col-lg-6 col-md-6"><?= $form->field($model, 'car_number') ->label('主机整车厂件号') ?></div>
    <div class="col-lg-6 col-md-6"><?= $form->field($model, 'car_category') ->label('适配整车品牌型号') ?></div>
</div>


<div class="row">
    <div class="col-lg-12 col-md-12"> <?= $form->field($model, 'standard') ->label('产品标准') ?> </div>
</div>


<div class="row">
    <div class="col-lg-3 col-md-3"><?= $form->field($model, 'price_1') ->label('产品价格 A档') ?></div>
    <div class="col-lg-3 col-md-3"><?= $form->field($model, 'price_2') ->label('产品价格 B档') ?></div>
    <div class="col-lg-3 col-md-3"><?= $form->field($model, 'price_3') ->label('产品价格 C档') ?></div>
    <div class="col-lg-3 col-md-3"><?= $form->field($model, 'price_4') ->label('产品价格 D档') ?></div>
</div>


<!--添加产品描述模块-->
<?= $form->field($model, 'describe')->label('产品描述')->widget(Redactor::className(), [
    'options' => [
        'minHeight' => 200,
        'imageUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'edm'], false),
        'fileUpload' => Url::to(['/admin/redactor/upload', 'dir' => 'edm'], false),
        'plugins' => ['fullscreen']
    ]
]) ?>

<div class="row">
    <!--添加产品标准图片模块-->
    <div class="col-lg-3 col-md-3">
        <?= $form->field($model, 'image_ids')->label('产品标准图')->widget(Upload::className(), ['folderSlug' => 'product', 'previewThumb' => false, 'previewWidth' => '100%', 'width' => 100, 'height' => 100]) ?>
    </div>
    <!--添加产品轮播图上传模块-->
    <div class="col-lg-3 col-md-3">
        <?= $form->field($model, 'gallery1_ids')->label('产品轮播图1')->widget(Upload::className(), ['folderSlug' => 'product', 'previewThumb' => false, 'previewWidth' => '100%', 'width' => 375, 'height' => 175]) ?>
    </div>
    <div class="col-lg-3 col-md-3">
        <?= $form->field($model, 'gallery2_ids')->label('产品轮播图2')->widget(Upload::className(), ['folderSlug' => 'product', 'previewThumb' => false, 'previewWidth' => '100%', 'width' => 375, 'height' => 175]) ?>
    </div>
    <div class="col-lg-3 col-md-3">
        <?= $form->field($model, 'gallery3_ids')->label('产品轮播图3')->widget(Upload::className(), ['folderSlug' => 'product', 'previewThumb' => false, 'previewWidth' => '100%', 'width' => 375, 'height' => 175]) ?>
    </div>

</div>


<!--添加表单提交模块-->
<?= Html::submitButton(Yii::t('easyii', 'Save'), ['class' => 'btn btn-primary']) ?>

<!--结束表单内容-->
<?php ActiveForm::end(); ?>

<?= app\modules\photolibrary\widgets\Editor::widget([]) ?>

webroot/app/modules/productdetail/views/a/_menu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;

$model = new $this->context->model;

$pendingCount = $model::find()->where(['status' => $model::STATUS_PENDING])->count();
$publishedCount = $model::find()->where(['status' => $model::STATUS_PUBLISHED])->count();
$deletedCount = $model::find()->where(['status' => $model::STATUS_DELETED])->count();

?>
<?php if ($action !== 'create' && $action !== 'edit' && $action !== 'carousels' && $action !== 'content-blocks' && $action !== 'related-content'): ?>
    <br/>

    <div>
        <span class="badge <?= ($action === 'index') ? 'badge-primary' : '' ?>"><a href="<?= Url::to(['/admin/'.$module.'/a/index']) ?>"><?= Yii::t('easyii', 'Published') ?> (<?=$publishedCount ?>)</a></span>
        <span class="badge <?= ($action === 'pending') ? 'badge-primary' : '' ?>"><a href="<?= Url::to(['/admin/'.$module.'/a/pending']) ?>"><?= Yii::t('easyii', 'Pending') ?> (<?=$pendingCount ?>)</a></span>
        <span class="badge <?= ($action === 'deleted') ? 'badge-primary' : '' ?>"><a href="<?= Url::to(['/admin/'.$module.'/a/deleted']) ?>"><?= Yii::t('easyii', 'Deleted') ?> (<?=$deletedCount ?>)</a></span>

        <div class="pull-right">
            <a href="<?= Url::to(['/admin/'.$module.'/a/create']) ?>"><i class="glyphicon glyphicon-plus font-12"></i> <?= Yii::t('easyii', 'Create') ?></a>
        </div>
    </div>
    <br>

<?php else: ?>
    <ul class="nav nav-pills">
        <li>
            <a href="<?= $this->context->getReturnUrl(['/admin/'.$module]) ?>"><i class="glyphicon glyphicon-chevron-left font-12"></i>Back</a>
        </li>
    </ul>
<?php endif; ?>

<br/>

webroot/app/modules/productdetail/views/a/_submenu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;
?>

<ul class="nav nav-tabs">
    <li <?= ($action === 'edit') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/a/edit', 'id' => $model->primaryKey]) ?>"><?= Yii::t('easyii', 'Basic') ?></a></li>

</ul>
<br>

webroot/app/modules/productdetail/views/a/content_blocks.php
<?php

$this->title = $model->title;
?>

<?= $this->render('_menu') ?>
<?= $this->render('_submenu', ['model' => $model]) ?>

webroot/app/modules/productdetail/views/a/create.php
<?php
$this->title = Yii::t('easyii', 'Create');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model]) ?>

webroot/app/modules/productdetail/views/a/edit.php
<?php
$this->title = $model->title;
?>
<?= $this->render('_menu') ?>

<?php echo $this->render('_submenu', ['model' => $model]) ?>

<?= $this->render('_form', ['model' => $model]) ?>

webroot/app/modules/productdetail/views/a/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

use yii\widgets\ActiveForm;
use yii\easyii\widgets\Redactor;

$this->title = Yii::t('easyii', '产品列表');
$module = $this->context->module->id;
?>


<?= $this->render('_menu') ?>

<form method="GET" action="/admin/<?= $module ?>/a/index">
    <div class="row">

        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">产品类别</div>
                    <input type="text" class="form-control" name="category" placeholder="产品类别" value="<?= Yii::$app->request->get('category', "") ?>">
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">适配整车品牌型号</div>
                    <input type="text" class="form-control" name="car_category" placeholder="适配整车品牌型号" value="<?= Yii::$app->request->get('car_category', "") ?>">
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">产品名称</div>
                    <input type="text" class="form-control" name="title" placeholder="产品名称" value="<?= Yii::$app->request->get('title', "") ?>">
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">产品件号</div>
                    <input type="text" class="form-control" name="number" placeholder="产品件号"  value="<?= Yii::$app->request->get('number', "") ?>">
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">主机整车厂件号</div>
                    <input type="text" class="form-control" name="car_number" placeholder="主机整车厂件号" value="<?= Yii::$app->request->get('car_number', "") ?>">
                </div>
            </div>
        </div>
        <div class="col-md-2 pull-right">
            <button type="submit" class="btn btn-primary pull-right">检索</button>
        </div>
    </div>
    <div class="row">
    </div>
    </form>

<?php if ($data->count > 0) : ?>
    <table class="table table-hover">
        <thead>
        <tr>
            <th width="50">#</th>
            <th><?= Yii::t('easyii', 'Title') ?></th>
            <th width="180"><?= Yii::t('easyii', 'Publish Time') ?></th>
            <th width="120"></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($data->models as $item) : ?>
            <tr data-id="<?= $item->primaryKey ?>">
                <td><?= $item->primaryKey ?></td>
                <td>
                    <a href="<?= Url::to(['/admin/' . $module . '/a/edit/', 'id' => $item->primaryKey]) ?>"><?= $item->title ?></a>
                </td>
                <td><?php echo Yii::$app->formatter->asDate($item->publish_time, 'yyyy-MM-dd hh:mm:ss'); ?></td>
                <td>
                    <div class="btn-group btn-group-sm" role="group">
                        <a href="<?= Url::to(['/admin/' . $module . '/a/up', 'id' => $item->primaryKey, 'status' => $item->status]) ?>"
                           class="btn btn-default move-up" title="<?= Yii::t('easyii', 'Move up') ?>"><span
                                    class="glyphicon glyphicon-arrow-up"></span></a>
                        <a href="<?= Url::to(['/admin/' . $module . '/a/down', 'id' => $item->primaryKey, 'status' => $item->status]) ?>"
                           class="btn btn-default move-down" title="<?= Yii::t('easyii', 'Move down') ?>"><span
                                    class="glyphicon glyphicon-arrow-down"></span></a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?= yii\widgets\LinkPager::widget([
        'pagination' => $data->pagination
    ]) ?>
<?php else : ?>
    <p><?= Yii::t('easyii', 'No records found') ?></p>
<?php endif; ?>