webroot/app/modules/photolibrary/controllers/AController.php
<?php
namespace app\modules\photolibrary\controllers;

use Yii;
use yii\easyii\components\CategoryController;
use app\modules\photolibrary\models\Category;

use yii\easyii\behaviors\SortableModel;
use yii\widgets\ActiveForm;
use yii\web\UploadedFile;
use yii\easyii\helpers\Image;

use yii\data\ActiveDataProvider;

use app\modules\photolibrary\models\Photo;



class AController extends CategoryController
{
    public $categoryClass = 'app\modules\photolibrary\models\Category';
    public $moduleName = 'photolibrary';
    public $viewRoute = '/a/photos';

    public function actionPhotos($id)
    {
        if(!($model = Category::findOne($id))){
            return $this->redirect(['/admin/'.$this->module->id]);
        }

        $select = (Yii::$app->request->get('select', 0));
        if ($select) {
            $this->layout = "empty";
        }

        $width = Yii::$app->request->get('width', 0);
        $height = Yii::$app->request->get('height', 0);


        $where = ['class' => get_class($model), 'item_id' => $model->primaryKey];
        if ($width != 0 && $height != 0) {
            $where['width'] = $width;
            $where['height'] = $height;
        }

        $query = Photo::find()->where($where);

        $search = Yii::$app->request->get('s', "");
        if ($search != "") {
            $where['title'] = $search;

            $query->andFilterWhere(['or',
                ['like','name',$search],
                ['like','description',$search]]);

        }



        $data = new ActiveDataProvider([
            'query' => $query->sort()
        ]);


        return $this->render('photos', [
            'model' => $model,
            'select' => $select,
            'data' => $data,
            'width' => $width,
            'height' => $height
        ]);
    }


    public function actionIndex()
    {
        $select = (Yii::$app->request->get('select') == 1);
        if ($select) {
            $this->layout = "empty";
        }

        $width = Yii::$app->request->get('width', 0);
        $height = Yii::$app->request->get('height', 0);


        $folderSlug = Yii::$app->request->get('folderSlug', "");

        $cat = Category::findOne(["slug" => $folderSlug]);
        if ($cat) {
            return $this->redirect('/admin/photolibrary/a/photos/'.$cat->category_id . '?select=' . Yii::$app->request->get('select') . '&width=' .$width . '&height=' .$height  ,302);
        }


        $class = $this->categoryClass;
        return $this->render('index', [
            'cats' => $class::cats(),
            'select' => $select,
            'width' => $width,
            'height' => $height
        ]);
    }


    public function actionCreate($parent = null)
    {

        $width = Yii::$app->request->get('width', 0);
        $height = Yii::$app->request->get('height', 0);

        $class = $this->categoryClass;
        $model = new $class;

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else{

                $model->status = $class::STATUS_ON;

                $parent = (int)Yii::$app->request->post('parent', null);
                if($parent > 0 && ($parentCategory = $class::findOne($parent))){
                    $model->order_num = $parentCategory->order_num;
                    $model->appendTo($parentCategory);
                } else {
                    $model->attachBehavior('sortable', SortableModel::className());
                    $model->makeRoot();
                }

                if(!$model->hasErrors()){
                    $this->flash('success', Yii::t('easyii', 'Category created'));
                    return $this->redirect(['/admin/'.$this->moduleName, 'id' => $model->primaryKey]);
                }
                else{
                    $this->flash('error', Yii::t('easyii', 'Create error. {0}', $model->formatErrors()));
                    return $this->refresh();
                }
            }
        }
        else {

            $select = (Yii::$app->request->get('select', 0));
            if ($select) {
                $this->layout = "empty";
            }

            return $this->render('create', [
                'model' => $model,
                'parent' => $parent,
                'select' => $select,
                'width' => $width,
                'height' => $height
            ]);
        }
    }


    public function actionEdit($id)
    {
        $class = $this->categoryClass;

        if(!($model = $class::findOne($id))){
            return $this->redirect(['/admin/' . $this->moduleName]);
        }

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else{

                if($model->save()){
                    $this->flash('success', Yii::t('easyii', 'Category updated'));
                }
                else{
                    $this->flash('error', Yii::t('easyii', 'Update error. {0}', $model->formatErrors()));
                }
                return $this->refresh();
            }
        }
        else {

            $select = (Yii::$app->request->get('select', 0));
            if ($select) {
                $this->layout = "empty";
            }

            return $this->render('edit', [
                'model' => $model,
                'select' => $select
            ]);
        }
    }




}

webroot/app/modules/photolibrary/controllers/PhotosController.php
<?php
namespace app\modules\photolibrary\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\UploadedFile;
use yii\web\Response;

use yii\easyii\helpers\Image;
use yii\easyii\components\Controller;
use yii\easyii\behaviors\SortableController;

use app\modules\photolibrary\models\Photo;
use app\modules\photolibrary\models\Category;


class PhotosController extends Controller
{
    public function behaviors()
    {
        return [
            [
                'class' => 'yii\filters\ContentNegotiator',
                'formats' => [
                    'application/json' => Response::FORMAT_JSON
                ],
            ],
            [
                'class' => SortableController::className(),
                'model' => Photo::className(),
            ]
        ];
    }

    public function actionUpload($folderSlug)
    {
        $success = null;

        $photo = new Photo;

        $photo->class = Category::className();
        $photo->item_id = 1;

        $cat = Category::findOne(["slug" => $folderSlug]);
        if ($cat) {
            $photo->item_id = $cat->category_id;
        }

        $photo->image = UploadedFile::getInstance($photo, 'image');
        $photo->name =$photo->image->name;

        $photo->description = Yii::$app->request->post('description');


        if($photo->image && $photo->validate(['image'])){
            $photo->image = Image::upload($photo->image, 'photos', Photo::PHOTO_MAX_WIDTH);

            if($photo->image){

                if(file_exists(($filename = Yii::getAlias('@webroot') . $photo->image)))
                {
                    $size = getimagesize ( $filename );
                    $photo->width = $size[0];
                    $photo->height = $size[1];
                }


                if($photo->save()){

                      $success = [
                        'message' => Yii::t('easyii', 'Photo uploaded'),
                        'photo' => [
                            'id' => $photo->primaryKey,
                            'image' => $photo->image,
                            'thumb' => Image::thumb($photo->image, Photo::PHOTO_THUMB_WIDTH, Photo::PHOTO_THUMB_HEIGHT),
                            'description' => $photo->description
                        ]
                    ];
                }
                else{
                    @unlink(Yii::getAlias('@webroot') . str_replace(Url::base(true), '', $photo->image));
                    $this->error = Yii::t('easyii', 'Create error. {0}', $carousel->formatErrors());
                }
            }
            else{
                $this->error = Yii::t('easyii', 'File upload error. Check uploads folder for write permissions');
            }
        }
        else{
            $this->error = Yii::t('easyii', 'File is incorrect');
        }

        return $this->formatResponse($success);
    }

    public function actionDescription($id)
    {
        if(($model = Photo::findOne($id)))
        {
            if(Yii::$app->request->post('description'))
            {
                $model->description = Yii::$app->request->post('description');
                if(!$model->update()) {
                    $this->error = Yii::t('easyii', 'Update error. {0}', $model->formatErrors());
                }
            }
            else{
                $this->error = Yii::t('easyii', 'Bad response');
            }
        }
        else{
            $this->error = Yii::t('easyii', 'Not found');
        }

        return $this->formatResponse(Yii::t('easyii', 'Photo description saved'));
    }

    public function actionImage($id)
    {
        $success = null;

        if(($photo = Photo::findOne($id)))
        {
            $oldImage = $photo->image;

            $photo->image = UploadedFile::getInstance($photo, 'image');

            if($photo->image && $photo->validate(['image'])){
                $photo->image = Image::upload($photo->image, 'photos', Photo::PHOTO_MAX_WIDTH);
                if($photo->image){
                    if($photo->save()){
                        @unlink(Yii::getAlias('@webroot').$oldImage);

                        $success = [
                            'message' => Yii::t('easyii', 'Photo uploaded'),
                            'photo' => [
                                'image' => $photo->image,
                                'thumb' => Image::thumb($photo->image, Photo::PHOTO_THUMB_WIDTH, Photo::PHOTO_THUMB_HEIGHT)
                            ]
                        ];
                    }
                    else{
                        @unlink(Yii::getAlias('@webroot').$photo->image);

                        $this->error = Yii::t('easyii', 'Update error. {0}', $photo->formatErrors());
                    }
                }
                else{
                    $this->error = Yii::t('easyii', 'File upload error. Check uploads folder for write permissions');
                }
            }
            else{
                $this->error = Yii::t('easyii', 'File is incorrect');
            }

        }
        else{
            $this->error =  Yii::t('easyii', 'Not found');
        }

        return $this->formatResponse($success);
    }

    public function actionDelete($id)
    {
        if(($model = Photo::findOne($id))){
            $model->delete();
        } else {
            $this->error = Yii::t('easyii', 'Not found');
        }
        return $this->formatResponse(Yii::t('easyii', 'Carousel deleted'));
    }

    public function actionUp($id, $class, $item_id)
    {
        return $this->move($id, 'up', ['class' => $class, 'item_id' => $item_id]);
    }

    public function actionDown($id, $class, $item_id)
    {
        return $this->move($id, 'down', ['class' => $class, 'item_id' => $item_id]);
    }
}

webroot/app/modules/photolibrary/views/a/_form.php
<?php
use yii\easyii\helpers\Image;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\easyii\widgets\SeoForm;

$class = $this->context->categoryClass;
$settings = $this->context->module->settings;
?>
<?php $form = ActiveForm::begin([
    'enableAjaxValidation' => true,
    'options' => ['enctype' => 'multipart/form-data']
]); ?>
<?= $form->field($model, 'title') ?>

<?php if(!empty($parent)) : ?>
    <div class="form-group field-category-title required">
        <label for="category-parent" class="control-label"><?= Yii::t('easyii', 'Parent category') ?></label>
        <select class="form-control" id="category-parent" name="parent">
            <option value="" class="smooth"><?= Yii::t('easyii', 'No') ?></option>
            <?php foreach($class::find()->sort()->asArray()->all() as $node) : ?>
                <option
                    value="<?= $node['category_id'] ?>"
                    <?php if($parent == $node['category_id']) echo 'SELECTED' ?>
                    style="padding-left: <?= $node['depth']*20 ?>px;"
                ><?= $node['title'] ?></option>
            <?php endforeach; ?>
        </select>
    </div>
<?php endif; ?>

<?= Html::submitButton(Yii::t('easyii', 'Save'), ['class' => 'btn btn-primary']) ?>
<?php ActiveForm::end(); ?>

webroot/app/modules/photolibrary/views/a/_menu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;
?>
<ul class="nav nav-pills">

    <?php if ($action === 'index'): ?>
        <li class="pull-right"><a href="<?= Url::to(['/admin/'.$this->context->moduleName.'/a/create', 'select'=>$select]) ?>"><i class="glyphicon glyphicon-plus font-12"></i> <?= Yii::t('easyii', 'Create Folder') ?></a></li>
    <?php endif; ?>

    <?php if ($action !== 'index'): ?>

        <li >
            <a href="<?= "/admin/photolibrary/a/index?select=" . $select . "&width=" . $width . "&height=" . $height ?>">
                <i class="glyphicon glyphicon-chevron-left font-12"></i>
                <?= Yii::t('easyii', 'Back') ?>
            </a>
        </li>

    <?php endif; ?>


</ul>


<br/>

webroot/app/modules/photolibrary/views/a/_submenu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;
?>

<ul class="nav nav-tabs">
    <li <?= ($action === 'photos') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/a/photos', 'id' => $model->primaryKey]) ?>"><span class="glyphicon glyphicon-camera"></span> <?= Yii::t('easyii', 'Photos') ?></a></li>
    <li <?= ($action === 'edit') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/a/edit', 'id' => $model->primaryKey]) ?>"><?= Yii::t('easyii', 'Edit category') ?></a></li>
</ul>
<br>

webroot/app/modules/photolibrary/views/a/create.php
<?php
$this->title = Yii::t('easyii', 'Create category');
?>
<?= $this->render('_menu', ['select' => $select, 'width' => $width, 'height' => $height]) ?>
<?= $this->render('_form', ['model' => $model, 'parent' => $parent]) ?>

webroot/app/modules/photolibrary/views/a/edit.php
<?php
$this->title = Yii::t('easyii', 'Edit category');
?>
<?= $this->render('_menu', ['select' => $select]) ?>

<?php if(!empty($this->params['submenu'])) echo $this->render('_submenu', ['model' => $model], $this->context); ?>
<?= $this->render('_form', ['model' => $model]) ?>

webroot/app/modules/photolibrary/views/a/index.php
<?php
use yii\easyii\components\CategoryModel;
use yii\helpers\Url;

\yii\bootstrap\BootstrapPluginAsset::register($this);

$this->title = Yii::$app->getModule('admin')->activeModules[$this->context->module->id]->title;

$baseUrl = '/admin/'.$this->context->moduleName;
?>

<?= $this->render('_menu', ['select' => $select]) ?>

<?php if(sizeof($cats) > 0) : ?>
    <table class="table table-hover font-12 ">
        <tbody>
            <?php foreach($cats as $cat) : ?>
                <tr>
                    <td width="50"><i class="glyphicon glyphicon-folder-open font-12"></i></td>
                    <td style="padding-left:  <?= $cat->depth * 20 ?>px;">
                        <?php if(count($cat->children)) : ?>
                            <i class="caret"></i>
                        <?php endif; ?>
                        <?php if(!count($cat->children) || !empty(Yii::$app->controller->module->settings['itemsInFolder'])) : ?>
                            <a href="<?= Url::to([$baseUrl . $this->context->viewRoute, 'id' => $cat->category_id, 'select'=>$select, 'width'=>$width, 'height'=>$height]) ?>" class="<?= ($cat->status == CategoryModel::STATUS_OFF ? 'smooth"' : '') ?>"><?= $cat->title ?></a>
                        <?php else : ?>
                            <span <?= ($cat->status == CategoryModel::STATUS_OFF ? 'class="smooth"' : '') ?>><?= $cat->title ?></span>
                        <?php endif; ?>
                    </td>
                    <td width="120" class="text-right">
                        <div class="dropdown actions">
                            <i id="dropdownMenu<?= $cat->category_id ?>" data-toggle="dropdown" aria-expanded="true" title="<?= Yii::t('easyii', 'Actions') ?>" class="glyphicon glyphicon-menu-hamburger"></i>
                            <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu<?= $cat->category_id ?>">
                                <li><a href="<?= Url::to([$baseUrl.'/a/edit', 'id' => $cat->category_id, 'select'=>$select]) ?>"><i class="glyphicon glyphicon-pencil font-12"></i> <?= Yii::t('easyii', 'Edit') ?></a></li>
                                <!--<li><a href="<?= Url::to([$baseUrl.'/a/create', 'parent' => $cat->category_id]) ?>"><i class="glyphicon glyphicon-plus font-12"></i> <?= Yii::t('easyii', 'Add subcategory') ?></a></li>-->
                                <li role="presentation" class="divider"></li>
                                <li><a href="<?= Url::to([$baseUrl.'/a/up', 'id' => $cat->category_id]) ?>"><i class="glyphicon glyphicon-arrow-up font-12"></i> <?= Yii::t('easyii', 'Move up') ?></a></li>
                                <li><a href="<?= Url::to([$baseUrl.'/a/down', 'id' => $cat->category_id]) ?>"><i class="glyphicon glyphicon-arrow-down font-12"></i> <?= Yii::t('easyii', 'Move down') ?></a></li>
                                <li role="presentation" class="divider"></li>
                                <?php if($cat->status == CategoryModel::STATUS_ON) :?>
                                    <!--<li><a href="<?= Url::to([$baseUrl.'/a/off', 'id' => $cat->category_id]) ?>" title="<?= Yii::t('easyii', 'Turn Off') ?>'"><i class="glyphicon glyphicon-eye-close font-12"></i> <?= Yii::t('easyii', 'Turn Off') ?></a></li>-->
                                <?php else : ?>
                                    <!--<li><a href="<?= Url::to([$baseUrl.'/a/on', 'id' => $cat->category_id]) ?>" title="<?= Yii::t('easyii', 'Turn On') ?>"><i class="glyphicon glyphicon-eye-open font-12"></i> <?= Yii::t('easyii', 'Turn On') ?></a></li>-->
                                <?php endif; ?>
                                <li><a href="<?= Url::to([$baseUrl.'/a/delete', 'id' => $cat->category_id]) ?>" class="confirm-delete" data-reload="1" title="<?= Yii::t('easyii', 'Delete item') ?>"><i class="glyphicon glyphicon-remove font-12"></i> <?= Yii::t('easyii', 'Delete') ?></a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
<?php else : ?>
    <p><?= Yii::t('easyii', 'No records found') ?></p>
<?php endif; ?>

webroot/app/modules/photolibrary/views/a/photos.php
<?php

use yii\easyii\helpers\Image;

use yii\helpers\Html;
use yii\helpers\Url;
use app\modules\photolibrary\models\Photo;

use app\modules\photolibrary\assets\Asset;

use app\modules\photolibrary\widgets\Editor;

use app\modules\photolibrary\widgets\Upload;



Asset::register($this);


$select = (Yii::$app->request->get('select') == 1);


$class = get_class($model);
$item_id = $model->primaryKey;

$linkParams = [
    'class' => $class,
    'item_id' => $item_id,
];


$this->title = Yii::$app->getModule('admin')->activeModules[$this->context->module->id]->title . ' / ' . $model->title;
?>

<?= $this->render('_menu', ['select' => $select, 'width' => $width, 'height' => $height]) ?>


<div class="module-photolibrary-page-photos" module="module-photolibrary-page-photos" data-class="<?= $class ?>" data-item_id="<?= $item_id ?>" module-data='{"width": <?= $width ?>, "height": <?= $height ?>, "folderSlug" : "<?= $model->slug ?>"}'>


    <div>

    <button class="upload btn btn-sm btn-success pull-right"><span class="glyphicon glyphicon-arrow-up"></span><?= Yii::t('easyii', 'Upload')?></button>

        <form method="GET" action="/admin/photolibrary/a/photos/<?= $item_id ?>">
    <div class="search-group input-group pull-right col-lg-3 col-sm-3">

        <input type="text" class="form-control" placeholder="Search" name="s" value="<?= Yii::$app->request->get('s', "") ?>">
        <input type="hidden" class="form-control" name="select" value="<?= $select ?>">
        <input type="hidden" class="form-control" name="width" value="<?= $width ?>">
        <input type="hidden" class="form-control" name="height" value="<?= $height ?>">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
      </span>

    </div>
        </form>


    <div class="size">
        <span class="badge <?= ($width == 0 && $height == 0) ? "badge-primary" : ""  ?>"><a href="/admin/photolibrary/a/photos/<?= $item_id ?>?select=<?= $select ?>&width=0&height=0">All</a></span>
        <span class="badge <?= ($width == 640 && $height == 640) ? "badge-primary" : ""  ?>"><a href="/admin/photolibrary/a/photos/<?= $item_id ?>?select=<?= $select ?>&width=640&height=640">640x640</a></span>
        <span class="badge <?= ($width == 1280 && $height == 720) ? "badge-primary" : ""  ?>"><a href="/admin/photolibrary/a/photos/<?= $item_id ?>?select=<?= $select ?>&width=1280&height=720">1280x720</a></span>
        <span class="badge <?= ($width == 375 && $height == 175) ? "badge-primary" : ""  ?>"><a href="/admin/photolibrary/a/photos/<?= $item_id ?>?select=<?= $select ?>&width=375&height=175">375x175</a></span>
        <span class="badge <?= ($width == 100 && $height == 100) ? "badge-primary" : ""  ?>"><a href="/admin/photolibrary/a/photos/<?= $item_id ?>?select=<?= $select ?>&width=100&height=100">100x100</a></span>
    </div>

        <div class="clearfix" />


    </div>






    <div class="container-fluid col-lg-12">
        <?php $date = ""; $idx=0; ?>
        <?php foreach($data->models as $item) : ?>
            <?php if ($date != Yii::$app->formatter->asDate($item->created_at, 'yyyy-MM-dd')): ?>
                <?php $date = Yii::$app->formatter->asDate($item->created_at, 'yyyy-MM-dd'); ?>
                <div class="date"><?php echo $date; ?></div>
            <?php endif; ?>

            <?php $datetime = Yii::$app->formatter->asDate($item->created_at, 'yyyy-MM-dd HH:mm:ss'); ?>

            <div class="thumb-container">
                <a href="<?= $item->image ?>" title="<?= $item->name ?>" data-index="<?= $idx ?>" data-datetime="<?= $datetime ?>" data-name="<?= $item->name ?>" data-width="<?= $item->width ?>" data-height="<?= $item->height ?>" data-id="<?= $item->primaryKey ?>" data-image="<?= $item->image ?>" data-thumb="<?= Image::thumb($item->image, Photo::PHOTO_THUMB_WIDTH, Photo::PHOTO_THUMB_HEIGHT) ?>" data-description="<?= $item->description ?>"><img class="photo-thumb" src="<?= Image::thumb($item->image, Photo::PHOTO_THUMB_WIDTH, Photo::PHOTO_THUMB_HEIGHT) ?>"></a>
                <?php if ($select): ?>
                    <button data-name="<?= $item->name ?>" data-width="<?= $item->width ?>" data-height="<?= $item->height ?>" data-id="<?= $item->primaryKey ?>" data-image="<?= $item->image ?>" data-thumb="<?= Image::thumb($item->image, Photo::PHOTO_THUMB_WIDTH, Photo::PHOTO_THUMB_HEIGHT) ?>" data-description="<?= $item->description ?>" title="<?= Yii::t('easyii', 'Select') ?>" class="btn select-sm btn-primary"><span class="glyphicon glyphicon-ok-circle"></span></button>
                <?php endif; ?>
                <div title="<?= $item->name ?>" class="thumb-name"><?= $item->name ?></div>
                <div class="thumb-size"><?= $item->width ?>x<?= $item->height ?></div>
            </div>
            <?php $idx++; ?>
        <?php endforeach; ?>
    </div>




    <?= yii\widgets\LinkPager::widget([
        'pagination' => $data->pagination
    ]) ?>



    <div class="gallery blueimp-gallery blueimp-gallery-controls">
        <div class="slides"></div>
        <h3 class="title"></h3>
        <span class="size"></span>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>

        <?php if ($select): ?>
            <a href="javascript:;" class="btn btn-sm btn-primary select"><span class="glyphicon glyphicon-ok-circle"></span> <?= Yii::t('easyii', 'Select') ?></a>
        <?php endif; ?>
        <a href="#edit-panel" class="btn btn-sm btn-success edit"><span class="fa fa-crop"></span> <?= Yii::t('easyii', 'Edit') ?></a>

    </div>



    <?= Editor::widget([]) ?>
</div>